
const validateCountryCode = (countryCode) => {
    if (countryCode.length !== 3) {
        return false;
    }

    return !!listOfCountryCodes().includes(countryCode);
}

const convertCountryNameToCode = (countryName) => {

    return listOfCountryCodes()[countryName];
}

const convert3DigitISOto2DigitISO = (countryCode) => {
    if (countryCode.length !== 3) {
        return false;
    }

    return countryCode.slice(0, 2);
}


//DO NOT EXPORT THIS!
const listOfCountryCodes = () => {
    return {
        "Russia": "RUS",
        "Canada": "CAN",
        "United States": "USA",
        "China": "CHN",
        "Brazil": "BRA",
        "Australia": "AUS",
        "India": "IND",
        "Argentina": "ARG",
        "Kazakhstan": "KAZ",
        "Algeria": "DZA",
        "Democratic Republic of the Congo": "COD",
        "Greenland": "GRL",
        "Saudi Arabia": "SAU",
        "Mexico": "MEX",
        "Indonesia": "IDN",
        "Sudan": "SDN",
        "Libya": "LBY",
        "Iran": "IRN",
        "Mongolia": "MNG",
        "Peru": "PER",
        "Chad": "TCD",
        "Niger": "NER",
        "Angola": "AGO",
        "Mali": "MLI",
        "South Africa": "ZAF",
        "Colombia": "COL",
        "Ethiopia": "ETH",
        "Bolivia": "BOL",
        "Mauritania": "MRT",
        "Egypt": "EGY",
        "Tanzania": "TZA",
        "Nigeria": "NGA",
        "Venezuela": "VEN",
        "Namibia": "NAM",
        "Pakistan": "PAK",
        "Mozambique": "MOZ",
        "Turkey": "TUR",
        "Chile": "CHL",
        "Zambia": "ZMB",
        "Myanmar": "MMR",
        "Afghanistan": "AFG",
        "Somalia": "SOM",
        "Central African Republic": "CAF",
        "Ukraine": "UKR",
        "Madagascar": "MDG",
        "Botswana": "BWA",
        "Kenya": "KEN",
        "France": "FRA",
        "Yemen": "YEM",
        "Thailand": "THA",
        "Spain": "ESP",
        "Turkmenistan": "TKM",
        "Cameroon": "CMR",
        "Papua New Guinea": "PNG",
        "Sweden": "SWE",
        "Uzbekistan": "UZB",
        "Morocco": "MAR",
        "Iraq": "IRQ",
        "Paraguay": "PRY",
        "Zimbabwe": "ZWE",
        "Japan": "JPN",
        "Germany": "DEU",
        "Republic of the Congo": "COG",
        "Finland": "FIN",
        "Vietnam": "VNM",
        "Malaysia": "MYS",
        "Norway": "NOR",
        "Poland": "POL",
        "Oman": "OMN",
        "Italy": "ITA",
        "Philippines": "PHL",
        "Ecuador": "ECU",
        "Burkina Faso": "BFA",
        "New Zealand": "NZL",
        "Gabon": "GAB",
        "Guinea": "GIN",
        "United Kingdom": "GBR",
        "Uganda": "UGA",
        "Ghana": "GHA",
        "Romania": "ROU",
        "Laos": "LAO",
        "Guyana": "GUY",
        "Belarus": "BLR",
        "Kyrgyzstan": "KGZ",
        "Senegal": "SEN",
        "Syria": "SYR",
        "Cambodia": "KHM",
        "Uruguay": "URY",
        "Tunisia": "TUN",
        "Suriname": "SUR",
        "Bangladesh": "BGD",
        "Nepal": "NPL",
        "Tajikistan": "TJK",
        "Greece": "GRC",
        "Nicaragua": "NIC",
        "North Korea": "PRK",
        "Malawi": "MWI",
        "Eritrea": "ERI",
        "Benin": "BEN",
        "Honduras": "HND",
        "Liberia": "LBR",
        "Bulgaria": "BGR",
        "Cuba": "CUB",
        "Guatemala": "GTM",
        "Iceland": "ISL",
        "South Korea": "KOR",
        "Hungary": "HUN",
        "Jordan": "JOR",
        "Portugal": "PRT",
        "Serbia": "SRB",
        "Azerbaijan": "AZE",
        "United Arab Emirates": "ARE",
        "Czech Republic": "CZE",
        "Panama": "PAN",
        "Sierra Leone": "SLE",
        "Ireland": "IRL",
        "Georgia": "GEO",
        "Sri Lanka": "LKA",
        "Lithuania": "LTU",
        "Latvia": "LVA",
        "Togo": "TGO",
        "Croatia": "HRV",
        "Bosnia and Herzegovina": "BIH",
        "Costa Rica": "CRI",
        "Slovakia": "SVK",
        "Dominican Republic": "DOM",
        "Estonia": "EST",
        "Denmark": "DNK",
        "Netherlands": "NLD",
        "Switzerland": "CHE",
        "Bhutan": "BTN",
        "Taiwan": "TWN",
        "Moldova": "MDA",
        "Lesotho": "LSO",
        "Armenia": "ARM",
        "Solomon Islands": "SLB",
        "Albania": "ALB",
        "Equatorial Guinea": "GNQ",
        "Burundi": "BDI",
        "Haiti": "HTI",
        "Rwanda": "RWA",
        "Macedonia": "MKD",
        "Djibouti": "DJI",
        "Belize": "BLZ",
        "El Salvador": "SLV",
        "Israel": "ISR",
        "Slovenia": "SVN",
        "Fiji": "FJI",
        "Kuwait": "KWT",
        "Swaziland": "SWZ",
        "Timor-Leste": "TLS",
        "Montenegro": "MNE",
        "Bahamas": "BHS",
        "Vanuatu": "VUT",
        "Qatar": "QAT",
        "Gambia": "GMB",
        "Jamaica": "JAM",
        "Lebanon": "LBN",
        "Cyprus": "CYP",
        "Brunei": "BRN",
        "Trinidad and Tobago": "TTO",
        "Cape Verde": "CPV",
        "Samoa": "WSM",
        "Luxembourg": "LUX"
    }
}

module.exports = {
    validateCountryCode,
    convertCountryNameToCode,
    convert3DigitISOto2DigitISO
}